import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Thankyou() {
  

  return (
    <>
      <Head>
        <title>Thank You - Curewith3D</title>
        <meta name="description" content="Generated by create next App"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://db.onlinewebfonts.com/c/758d40d7ca52e3a9bff2655c7ab5703c?family=Cambria+W02+Regular" rel="stylesheet"></link>
      </Head>

    


 
        {/* <!-- about area --> */}
        <div id="about-us" class="about-area pt-100 pb-100 lightdarkbg">
            <div class="container">
                <div class="row align-items-center">
                 
                    <div class="col-lg-12 text-center">
                        <div class="about-right wow fadeInUp" data-wow-delay=".25s">
                            <div class="site-heading mb-3">                        
                                <h2 class="" style={{ textAlign: "center" }}>Thank you</h2>
                            </div>
                            <p class="about-text">
                                We appreciate your trust in us. Our team will contact you soon to discuss your loved one's recovery plan.
                            </p>
                            <p class="about-text">
                                Your family's well-being is our top priority now.
                            </p>
                            <p>
                                Don’t wait for a callback — book your slot immediately
                            </p>
                            <br></br>
                            <div className="hero-btn wow fadeInUp" data-delay="1s">
                              <a href="tel:+91-920-555-98-04" className="theme-btn">+91-920-555-98-04<i
                                                className="fas fa-arrow-right"></i></a>
                                    </div>
                            <br></br>
                         
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {/* <!-- about area end --> */}




    </>
  );
}
